### root API
GET http://localhost:3000

### fetch all leads
GET http://localhost:3000/leads

### fetch 1 leads
GET http://localhost:3000/leads/1

### create leads
POST http://localhost:3000/leads
Content-Type: application/json

{
  "email": "9@1.com"
}

# ### update one leads
# PATCH http://localhost:3000/leads/1

# ### DELETE one leads
# DELETE http://localhost:3000/leads/1

### get all leads prod
GET https://vz8tn8rfja.execute-api.us-east-2.amazonaws.com/leads
