# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aomcheer
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-nodejs-neon
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DEBUG: ${env.DEBUG, 0}
    DATABASE_URL: ${env:DATABASE_URL, "fallback value"}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
